# Generated by Django 4.2.1 on 2023-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('method_payment', models.CharField(max_length=20)),
            ],
        ),
    ]
