# Generated by Django 4.2.3 on 2023-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_productadmin_product'),
        ('cart', '0002_rename_add_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
