# Generated by Django 4.2.3 on 2023-07-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_rename_registration_mamamboga'),
        ('inventory', '0003_rename_productadmin_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor.mamamboga'),
            preserve_default=False,
        ),
    ]
